# Generated by Django 3.1 on 2021-06-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='domic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='fecha_suscr',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='monto_i',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='num_op',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='num_pa',
        ),
    ]
